### ISSUE TITLE
Возврат true в сценарии, где текущий баланс должен стать меньше минимального баланса

### ISSUE THREAD

**Issue by dousmartin** [brunduk/DiplomForTwoPeople#10]
# Описание
Текущий баланс не может быть меньше минимального баланса, ответ программы true

# Локация дефекта
https://github.com/brunduk/DiplomForTwoPeople/blob/c7adf32e6f9855165f12786fe9b4d96ac6f3ad39/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L65

# Шаги воспроизведения
1. [Открыть код программы](https://github.com/brunduk/DiplomForTwoPeople/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной `initialBalance`(текущий баланс) 2_000
3. Выставить значение переменной `minBalance`(минимальный баланс) 1_000
4. Выставить значение переменной `maxBalance`(максимальный баланс) 10_000
5. Выставить значение переменной `rate`(ставка) 5
6. Выставить значение переменной `amount`(сумма покупки) 3_000
7. Запустить программу
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* Текущий баланс не меняется, программа возвращает false
*Фактический результат:* Текущий баланс не меняется, программа возвращает true

# Скриншот
![image](https://github.com/brunduk/DiplomForTwoPeople/assets/138994531/92f32e2a-9cb4-4315-b965-0c66d890c51c)

# Окружение
* **Операционная система:** macOS Monterey 12.6.3
* **IDE:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** Open JDK 11

**Comment by brunduk** [comment]
Баг исправлен.
