### ISSUE TITLE
Отрицательный баланс при сумме оплаты больше минимального остатка 

### ISSUE THREAD

**Issue by dousmartin** [brunduk/DiplomForTwoPeople#5]
# Описание
Если сумма оплаты больше минимального баланса, то баланс на счете становится отрицательным

# Локация дефекта
https://github.com/brunduk/DiplomForTwoPeople/blob/e4bea03dfc7ba7f5ee79401c52da99e433981a4f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L76

# Шаги воспроизведения
1. [Открыть код программы](https://github.com/brunduk/DiplomForTwoPeople/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной `initialBalance`(текущий баланс) 2_000
3. Выставить значение переменной `minBalance`(минимальный баланс) 1_000
4. Выставить значение переменной `maxBalance`(максимальный баланс) 10_000
5. Выставить значение переменной `rate`(ставка) 5
6. Выставить значение переменной `amount`(сумма покупки) 3_000
7. Запустить программу
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* Текущий баланс не меняется на отрицательный, остается текущим
*Фактический результат:* Текущий баланс меняется на отрицательный

# Скриншот
![image](https://github.com/brunduk/DiplomForTwoPeople/assets/138994531/6dc705f6-3107-4197-8293-33c485009a53)

# Окружение
* **Операционная система:** macOS Monterey 12.6.3
* **IDE:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** Open JDK 11

**Comment by brunduk** [comment]
Баг исправлен.
