### ISSUE TITLE
Текущий остаток после пополнения равен сумме пополнения

### ISSUE THREAD

**Issue by dousmartin** [brunduk/DiplomForTwoPeople#7]
# Описание
После пополнения счета текущий остаток равен сумме пополнения

# Локация дефекта
https://github.com/brunduk/DiplomForTwoPeople/blob/e4bea03dfc7ba7f5ee79401c52da99e433981a4f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

# Шаги воспроизведения
1. [Открыть код программы](https://github.com/brunduk/DiplomForTwoPeople/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной `initialBalance`(текущий баланс) 2_000
3. Выставить значение переменной `minBalance`(минимальный баланс) 1_000
4. Выставить значение переменной `maxBalance`(максимальный баланс) 10_000
5. Выставить значение переменной `rate`(ставка) 5
6. Выставить значение переменной `amount`(сумма покупки) 3_000
7. Запустить программу
8. Посмотреть на вывод в консоли

*Ожидаемый результат:* Текущий баланс увеличивается на сумму пополнения
*Фактический результат:* Текущий баланс равен сумме пополнения

# Скриншот
![image](https://github.com/brunduk/DiplomForTwoPeople/assets/138994531/62e28291-ce47-4670-ad17-4d365a4ab409)

# Окружение
* **Операционная система:** macOS Monterey 12.6.3
* **IDE:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** Open JDK 11

**Comment by brunduk** [comment]
Баг исправлен.
