### ISSUE TITLE
Текст исключения при значении максимального баланса меньше минимального баланса

### ISSUE THREAD

**Issue by dousmartin** [brunduk/DiplomForTwoPeople#9]
# Описание
Тестирование исключения при отрицательном значении процентной ставки

# Локация дефекта
https://github.com/brunduk/DiplomForTwoPeople/blob/e4bea03dfc7ba7f5ee79401c52da99e433981a4f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. [Открыть код программы](https://github.com/brunduk/DiplomForTwoPeople/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Выставить значение переменной `initialBalance`(текущий баланс) 2_000
3. Выставить значение переменной `minBalance`(минимальный баланс) 1_000
4. Выставить значение переменной `maxBalance`(максимальный баланс) 10_000
5. Выставить значение переменной `rate`(ставка) -10
6. Запустить программу
7. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит, отображение ошибки типа `IllegalArgumentException` с текстом "Накопительная ставка не может быть отрицательной, а у вас: + `rate`".
*Фактический результат:* Тест не проходит, отображение ошибки типа `IllegalArgumentException` с текстом "Накопительная ставка не может быть отрицательной, а у вас: + `rate`".

# Скриншот
![image](https://github.com/brunduk/DiplomForTwoPeople/assets/138994531/1d1abeeb-37ab-4b68-bcc0-216018621c64)

# Окружение
* **Операционная система:** macOS Monterey 12.6.3
* **IDE:** IntelliJ IDEA 2023.1.1 (Community Edition)
* **JAVA:** Open JDK 11

**Comment by brunduk** [comment]
Баг исправлен.
